### Edible Plants Database EDA

#### Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("data/edible_plants.csv")
dataset.head()

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
0,Pisum sativum,Pea,Legume,Full sun,Very High,6.0,7.5,Medium,Loamy,Annual,Half hardy,24,4-24,6,55-75,"A good source of vitamin K, manganese, and die...",80.0,Drought intolerant,"The pea is the small spherical seed, or the se...","Require a sunny, nutrient-rich, moisture-reten..."
1,Phaseolus coccineus,Beans (Runner),Legume,Full sun,Medium,6.0,6.8,Medium,Loamy and clay,Annual,Tender,26,16-30,7,65-85,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,Runner bean plants are more productive than gr...,"Beans are a tender, warm-weather crop. They ar..."
2,Phaseolus vulgari,Beans (French),Legume,Full sun,Medium,6.0,7.5,Medium,Any well-drained and fertile,Annual,Tender,26,16-30,7,40-55,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,"French beans are the unripe fruit, and protect...","Beans are a tender, warm-weather crop. They ar..."
3,Vicia faba,Beans (Broad),Legume,Full sun/partial shade/full shade,Very Low,6.0,7.0,Medium,Any well-drained and fertile,Annual,Hardy,10,8-15,7,85-115,"A good source of vitamin-B6 (pyridoxine), thia...",88.0,Drought intolerant,Broad beans - also known as the fava bean - ar...,Broad beans are a cool weather crop. They grow...
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...

In [3]:
dataset.describe()

       preferred_ph_lower  preferred_ph_upper     energy
count          140.000000          140.000000  12.000000
mean             5.832143            7.114286  35.666667
std              0.422440            0.476433  26.568379
min              4.500000            6.000000   0.000000
25%              5.500000            7.000000  26.500000
50%              6.000000            7.000000  31.000000
75%              6.000000            7.500000  38.750000
max              7.000000            8.500000  88.000000

In [4]:
dataset.dtypes

taxonomic_name              object
common_name                 object
cultivation                 object
sunlight                    object
water                       object
preferred_ph_lower         float64
preferred_ph_upper         float64
nutrients                   object
soil                        object
season                      object
temperature_class           object
temperature_germination     object
temperature_growing         object
days_germination            object
days_harvest                object
nutritional_info            object
energy                     float64
sensitivities               object
description                 object
requirements                object
dtype: object

In [5]:
dataset.columns

Index(['taxonomic_name', 'common_name', 'cultivation', 'sunlight', 'water',
       'preferred_ph_lower', 'preferred_ph_upper', 'nutrients', 'soil',
       'season', 'temperature_class', 'temperature_germination',
       'temperature_growing', 'days_germination', 'days_harvest',
       'nutritional_info', 'energy', 'sensitivities', 'description',
       'requirements'],
      dtype='object')

In [6]:
dataset.isna().sum()

taxonomic_name               0
common_name                  0
cultivation                  0
sunlight                     0
water                        0
preferred_ph_lower           0
preferred_ph_upper           0
nutrients                    0
soil                        46
season                      73
temperature_class            0
temperature_germination     36
temperature_growing         82
days_germination            38
days_harvest                27
nutritional_info           129
energy                     128
sensitivities              127
description                  0
requirements                 0
dtype: int64

#### Do plants that require more sunlight also require higher temperatures?

##### What cultivation classes require the most water?